version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/tz_shop
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_DATABASE=tz_shop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    entrypoint:
      - ./entrypoint.sh
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_DB=tz_shop
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=postgres
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
