# Generated by Django 3.2.4 on 2021-06-23 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность товара')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление товара')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения товара')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='себестоимость товара', max_digits=100, verbose_name='Себестоимость товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена товара:')),
                ('number_of_units', models.BigIntegerField(verbose_name='Количество товара')),
                ('slug', models.SlugField(verbose_name='Slug товара:')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.BigIntegerField(verbose_name='Количество заказанных товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность заказа')),
                ('delivery_address', models.CharField(max_length=256, verbose_name='Адресс доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('products', models.ManyToManyField(to='shop_app.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'product_order',
            },
        ),
        migrations.CreateModel(
            name='BuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Покупа товара',
                'verbose_name_plural': 'Покупка товаров',
                'db_table': 'buy_product',
            },
        ),
    ]
