# Generated by Django 3.2.4 on 2021-06-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
