# Generated by Django 3.2.4 on 2021-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_buyproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='quantity',
            field=models.BigIntegerField(default=5, verbose_name='Количество единиц товара'),
            preserve_default=False,
        ),
    ]
